pipeline {
    agent any

    stages {
        stage('GIT') {
            steps {
                git branch: 'FediAbdennabi-5SIM1-G2', url: 'https://github.com/KvRae/5SIM1-G2-KADDEM.git'
            }
        }

        stage('Maven') {
            steps {
                dir('kaddem') {
                    sh 'mvn clean compile'
                }
            }
        }

         stage('SONARQUBE') {
            steps {
                    dir('kaddem'){
                        withSonarQubeEnv('sonarqube') {
                            sh 'mvn sonar:sonar'
                        }
                    }


            }
        }

        stage('Nexus') {
                   steps {
                        dir('kaddem') {
                            sh "mvn deploy -DskipTests"
                        }
                   }
                }


    }
}